// Builds src/data/foods.generated.ts from the curated mapping files in data-src/foodmap/*.json
// and the USDA SR Legacy data (.usda/usda-foods.json, made by scripts/fetch-usda.mjs).
//   node scripts/build-foods.mjs
//
// A mapping entry names a food in Bulgarian and points at its nutrient source:
//   fdc     — one USDA food id
//   recipe  — [[fdc id, grams], ...] (+ optional cooked `yield` in grams)
//   values  — hand-entered per-100 g values (partial; marked as having no full micronutrient data)
import fs from 'node:fs';
import path from 'node:path';

const MAP_DIR = path.resolve('data-src/foodmap');
const USDA = path.resolve('.usda/usda-foods.json');
const OUT = path.resolve('src/data/foods.generated.ts');

// Keep in sync with NUTRIENT_KEYS consumers in src/data/nutrients.ts (the generated file exports this list).
const KEYS = [
  'kcal', 'protein', 'fat', 'carbs', 'fiber', 'sugar', 'satFat',
  'sodium', 'potassium', 'magnesium', 'calcium', 'phosphorus', 'iron', 'zinc', 'copper', 'manganese', 'selenium',
  'vitA', 'retinol', 'vitC', 'vitD', 'vitE', 'vitK', 'b1', 'b2', 'b3', 'b6', 'folate', 'b12', 'omega3',
];
const CATEGORIES = new Set([
  'meat', 'deli', 'fish', 'eggs', 'dairy', 'cheese', 'fats', 'vegetables', 'fruits', 'nuts', 'legumes',
  'grains', 'sweets', 'sauces', 'drinks', 'alcohol', 'dishes',
]);
const TAGS = new Set(['m', 'rm', 'pm', 'f', 'd', 'e', 'h', 'r', 'b', 'wg', 'rg', 's', 'fr', 'po', 'uf']);

if (!fs.existsSync(USDA)) {
  console.error('Missing .usda/usda-foods.json — run `node scripts/fetch-usda.mjs` first.');
  process.exit(1);
}
const usda = JSON.parse(fs.readFileSync(USDA, 'utf8'));

function usdaValues(fdc) {
  const f = usda[fdc];
  if (!f) throw new Error(`USDA food ${fdc} not found`);
  const n = { ...f.n };
  n.omega3 = (n.ala ?? 0) + (n.epa ?? 0) + (n.dha ?? 0) + (n.dpa ?? 0);
  if (n.kcal == null) n.kcal = 4 * (n.protein ?? 0) + 9 * (n.fat ?? 0) + 4 * (n.carbs ?? 0);
  return n;
}

function valuesOf(entry) {
  if (entry.fdc != null) return { n: usdaValues(entry.fdc), full: true };
  if (entry.recipe) {
    const sum = Object.fromEntries(KEYS.map((k) => [k, 0]));
    let grams = 0;
    for (const [fdc, g] of entry.recipe) {
      const n = usdaValues(fdc);
      for (const k of KEYS) sum[k] += ((n[k] ?? 0) * g) / 100;
      grams += g;
    }
    const total = entry.yield ?? grams;
    if (!(total > 0)) throw new Error(`${entry.id}: recipe has no weight`);
    return { n: Object.fromEntries(KEYS.map((k) => [k, (sum[k] / total) * 100])), full: true };
  }
  if (entry.values) return { n: { ...entry.values }, full: false };
  throw new Error(`${entry.id}: no nutrient source`);
}

/** 3 significant digits, at most 3 decimals — keeps the bundle small without losing meaningful precision. */
function compact(v) {
  if (!v || !Number.isFinite(v) || v < 0) return 0;
  const r = Number(v.toPrecision(3));
  return Math.round(r * 1000) / 1000;
}

const files = fs.readdirSync(MAP_DIR).filter((f) => f.endsWith('.json')).sort();
const seen = new Map();
const rows = [];
let errors = 0;

for (const file of files) {
  const list = JSON.parse(fs.readFileSync(path.join(MAP_DIR, file), 'utf8'));
  for (const e of list) {
    try {
      if (!/^[a-z0-9-]+$/.test(e.id ?? '')) throw new Error('bad id');
      if (seen.has(e.id)) throw new Error(`duplicate id (also in ${seen.get(e.id)})`);
      seen.set(e.id, file);
      if (!CATEGORIES.has(e.cat)) throw new Error(`unknown category ${e.cat}`);
      const tags = (e.tags ?? []).filter((t) => {
        if (!TAGS.has(t)) console.warn(`  ${e.id}: dropping unknown tag ${t}`);
        return TAGS.has(t);
      });
      const { n, full } = valuesOf(e);
      const portions = (e.portions ?? [])
        .filter(([label, g]) => label && g > 0)
        .map(([label, g]) => `${String(label).replace(/[|:]/g, ' ')}:${compact(g)}`)
        .join('|');
      const aliases = (e.aliases ?? []).map((a) => String(a).toLowerCase().replace(/\|/g, ' ')).join('|');
      rows.push([e.id, String(e.name).trim(), e.cat, tags.join(','), aliases, portions, full ? 1 : 0, KEYS.map((k) => compact(n[k]))]);
    } catch (err) {
      errors++;
      console.error(`ERROR ${file} ${e?.id}: ${err.message}`);
    }
  }
}

if (errors) {
  console.error(`${errors} errors — nothing written.`);
  process.exit(1);
}

rows.sort((a, b) => a[1].localeCompare(b[1], 'bg'));

const body = rows.map((r) => `  ${JSON.stringify(r)},`).join('\n');
const out = `// AUTO-GENERATED by scripts/build-foods.mjs from data-src/foodmap/*.json and USDA FoodData Central (SR Legacy).
// Do not edit by hand — change the mapping files and run \`node scripts/build-foods.mjs\`.

export const NUTRIENT_KEYS = ${JSON.stringify(KEYS)} as const;

/** [id, name, category, tags (comma), aliases (|), portions ("label:grams|..."), hasFullData (1/0), per-100 g values in NUTRIENT_KEYS order] */
export type RawFood = [string, string, string, string, string, string, number, number[]];

export const FOOD_DATA: RawFood[] = [
${body}
];
`;
fs.writeFileSync(OUT, out);
console.log(`Wrote ${rows.length} foods to ${path.relative(process.cwd(), OUT)}`);
